esphome:
  name: indoor-humidity-1
  friendly_name: Indoor Humidity 1

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret indoor-humidity-1-api-key

ota:
  - platform: esphome
    password: !secret indoor-humidity-1-ota-password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Indoor-Humidity-1"
    password: !secret indoor-humidity-1-ap-password

captive_portal:

sensor:
  - platform: dht
    pin: D1
    temperature:
      name: "Landing Temp"
    humidity:
      name: "Landing Humidity"
    update_interval: 60s
    