esphome:
  name: laser-sensor
  friendly_name: Angry Ghosts

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret laser-sensor-api-key

ota:
  - platform: esphome
    password: !secret laser-sensor-ota-password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Laser-Sensor Fallback Hotspot"
    password: !secret laser-sensor-ap-password

captive_portal:

# Example configuration entry for ESP32
i2c:
  sda: 5
  scl: 4
  scan: true
  id: bus_a

pca9685:
  - id: servo_hub0
    frequency: 50

# Individual outputs
output:
  - platform: pca9685
    id: servo_hub0_0
    pca9685_id: servo_hub0
    channel: 0
  - platform: pca9685
    id: servo_hub0_1
    pca9685_id: servo_hub0
    channel: 1
  - platform: pca9685
    id: servo_hub0_2
    pca9685_id: servo_hub0
    channel: 2
  - platform: pca9685
    id: servo_hub0_3
    pca9685_id: servo_hub0
    channel: 3
  - platform: pca9685
    id: servo_hub0_4
    pca9685_id: servo_hub0
    channel: 4
  - platform: pca9685
    id: servo_hub0_5
    pca9685_id: servo_hub0
    channel: 5
  - platform: pca9685
    id: servo_hub0_6
    pca9685_id: servo_hub0
    channel: 6
  - platform: pca9685
    id: servo_hub0_7
    pca9685_id: servo_hub0
    channel: 7
  - platform: pca9685
    id: servo_hub0_8
    pca9685_id: servo_hub0
    channel: 8
  - platform: pca9685
    id: servo_hub0_9
    pca9685_id: servo_hub0
    channel: 9
  - platform: pca9685
    id: servo_hub0_10
    pca9685_id: servo_hub0
    channel: 10
  - platform: pca9685
    id: servo_hub0_11
    pca9685_id: servo_hub0
    channel: 11
  - platform: pca9685
    id: servo_hub0_12
    pca9685_id: servo_hub0
    channel: 12
  - platform: pca9685
    id: servo_hub0_13
    pca9685_id: servo_hub0
    channel: 13
  - platform: pca9685
    id: servo_hub0_14
    pca9685_id: servo_hub0
    channel: 14
  - platform: pca9685
    id: servo_hub0_15
    pca9685_id: servo_hub0
    channel: 15

servo:
  - id: servo_0
    output: servo_hub0_8
  - id: servo_1
    output: servo_hub0_9
  - id: servo_2
    output: servo_hub0_10
  - id: servo_3
    output: servo_hub0_11

number:
  - platform: template
    name: Ghost 1 Movement
    min_value: -100
    initial_value: 0
    max_value: 100
    step: 1
    optimistic: true
    set_action:
      then:
        - servo.write:
            id: servo_0
            level: !lambda 'return x / 100.0;'
            
  - platform: template
    name: Ghost 2 Movement
    min_value: -100
    initial_value: 0
    max_value: 100
    step: 1
    optimistic: true
    set_action:
      then:
        - servo.write:
            id: servo_1
            level: !lambda 'return x / 100.0;'

  - platform: template
    name: Ghost 3 Movement
    min_value: -100
    initial_value: 0
    max_value: 100
    step: 1
    optimistic: true
    set_action:
      then:
        - servo.write:
            id: servo_2
            level: !lambda 'return x / 100.0;'

  - platform: template
    name: Ghost 4 Movement
    min_value: -100
    initial_value: 0
    max_value: 100
    step: 1
    optimistic: true
    set_action:
      then:
        - servo.write:
            id: servo_3
            level: !lambda 'return x / 100.0;'

light:
  - platform: monochromatic
    name: Ghost 1 Friendly
    id: g1_friendly
    output: servo_hub0_0
    effects:
      - pulse:
          name: slow Pulse
          transition_length: 5s
          update_interval: 5s
    on_turn_on:
      light.turn_on:
        id: g1_friendly
        effect: slow Pulse

  - platform: monochromatic
    name: Ghost 1 Blue Pupils
    id: g1_blue
    output: servo_hub0_1
    effects:
      - pulse:
          name: slow Pulse
          transition_length: 5s
          update_interval: 5s
    # on_turn_on:
    #   light.turn_on:
    #     id: g1_blue
    #     effect: slow Pulse
      
  - platform: monochromatic
    name: Ghost 1 Angry
    id: g1_angry
    output: servo_hub0_2
    effects:
      - strobe:
          name: fast strobe
          colors:
            - state: true
              brightness: 100%
              duration: 500ms
            - state: true
              brightness: 10%
              duration: 250ms
    on_turn_on:
      light.turn_on:
        id: g1_angry
        effect: fast strobe

  - platform: monochromatic
    name: Ghost 1 Red Pupils
    id: g1_red
    output: servo_hub0_3
    effects:
      - strobe:
          name: fast strobe
          colors:
            - state: true
              brightness: 100%
              duration: 500ms
            - state: true
              brightness: 10%
              duration: 250ms
    # on_turn_on:
    #   light.turn_on:
    #     id: g1_red
    #     effect: fast strobe

  - platform: monochromatic
    name: Ghost 2 Friendly
    id: g2_friendly
    output: servo_hub0_4
    effects:
      - pulse:
          name: slow Pulse
          transition_length: 5s
          update_interval: 5s
    on_turn_on:
      light.turn_on:
        id: g2_friendly
        effect: slow Pulse

  - platform: monochromatic
    name: Ghost 2 Blue Pupils
    id: g2_blue
    output: servo_hub0_5
    effects:
      - pulse:
          name: slow Pulse
          transition_length: 5s
          update_interval: 5s
    on_turn_on:
      light.turn_on:
        id: g2_blue
        effect: slow Pulse
      
  - platform: monochromatic
    name: Ghost 2 Angry
    id: g2_angry
    output: servo_hub0_6
    effects:
      - strobe:
          name: fast strobe
          colors:
            - state: true
              brightness: 100%
              duration: 500ms
            - state: true
              brightness: 10%
              duration: 250ms
    on_turn_on:
      light.turn_on:
        id: g2_angry
        effect: fast strobe

  - platform: monochromatic
    name: Ghost 2 Red Pupils
    id: g2_red
    output: servo_hub0_7
    effects:
      - strobe:
          name: fast strobe
          colors:
            - state: true
              brightness: 100%
              duration: 500ms
            - state: true
              brightness: 10%
              duration: 250ms
    on_turn_on:
      light.turn_on:
        id: g2_red
        effect: fast strobe